services:
  comfyui:
    image: nvcr.io/nvidia/pytorch:24.10-py3
    volumes:
      - ./ComfyUI:/ComfyUI
      - ./ComfyUI-Manager:/ComfyUI/custom_nodes/ComfyUI-Manager
      - ./input:/ComfyUI/input # 自分カスタム用
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command:
      - /bin/bash
      - -c
      - |
        cd /ComfyUI/
        # templateで使用するモデルをダウンロード
        curl -L -o ./models/checkpoints/v1-5-pruned-emaonly.safetensors \
        https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors
        pip3 install -r requirements.txt
        pip3 install -r custom_nodes/ComfyUI-Manager/requirements.txt
        python3 main.py --listen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    #command: ["sleep", "infinity"] # debug用コンテナが終了しないようにする
    ports:
      # host:container
      - "8188:8188"
    networks:
      my-network:
        aliases:
          - comfyui  # コンテナのホスト名
networks:
  my-network: